"""Add risks table

Revision ID: 004
Revises: 003
Create Date: 2026-03-30 06:17:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('threat_source', sa.String(length=255), nullable=False),
    sa.Column('vulnerability', sa.String(length=255), nullable=False),
    sa.Column('asset_at_risk', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('inherent_risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_owner_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_tenant_id'), 'risks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # RLS Policies
    op.execute("ALTER TABLE risks ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE risks FORCE ROW LEVEL SECURITY")

    # Tenant isolation policies for risks
    op.execute("""
        CREATE POLICY tenant_isolation ON risks
        USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
    """)

    # Superadmin bypass for risks
    op.execute("""
        CREATE POLICY superadmin_bypass ON risks
        USING (current_setting('app.is_superadmin', true)::boolean = true)
    """)


def downgrade() -> None:
    # Remove RLS Policies
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON risks")
    op.execute("DROP POLICY IF EXISTS superadmin_bypass ON risks")
    op.execute("ALTER TABLE risks DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risks_tenant_id'), table_name='risks')
    op.drop_table('risks')
    # ### end Alembic commands ###
